<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9j7MtDf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9j7MtDf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9j7MtDf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9j7MtDf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9j7MtDf\App_KernelDevDebugContainer([
    'container.build_hash' => '9j7MtDf',
    'container.build_id' => 'cdd7a5e0',
    'container.build_time' => 1708602569,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9j7MtDf');
