<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0YCJxYY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0YCJxYY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0YCJxYY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0YCJxYY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0YCJxYY\App_KernelDevDebugContainer([
    'container.build_hash' => '0YCJxYY',
    'container.build_id' => 'd71097d6',
    'container.build_time' => 1709551377,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0YCJxYY');
