<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGdPjcK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGdPjcK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWGdPjcK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWGdPjcK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWGdPjcK\App_KernelDevDebugContainer([
    'container.build_hash' => 'WGdPjcK',
    'container.build_id' => 'b1e3bc55',
    'container.build_time' => 1709858827,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGdPjcK');
